import type { Metadata } from 'next'
import PrimaryNavbar from '@/components/PrimaryNavbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <PrimaryNavbar />
      <div className="h-16 min-w-max bg-intensity-bar"></div>
      <body className="bg-primary-background">{children}</body>
    </html>
  )
}
