import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import PrimaryNavbar from '@/components/PrimaryNavbar'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-primary-background">
        <PrimaryNavbar />
        {children}
      </body>
    </html>
  )
}
